CREATE TABLE `abastecimentos_cta` (
	`id` varchar(50) NOT NULL,
	`sequencial` int,
	`data_inicio` date,
	`hora_inicio` time,
	`data_fim` date,
	`hora_fim` time,
	`volume` decimal(10,3),
	`odometro` int,
	`odometro_final` int,
	`placa` varchar(20),
	`combustivel` varchar(50),
	`valor_unitario` decimal(10,4),
	`valor_total` decimal(10,2),
	`motorista` varchar(200),
	`posto` varchar(200),
	`observacoes` text,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `abastecimentos_cta_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `proposta_historico` (
	`id` int AUTO_INCREMENT NOT NULL,
	`proposta_id` int NOT NULL,
	`acao` varchar(100),
	`descricao` text,
	`alterado_por` varchar(255),
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `proposta_historico_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `propostas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`numero_orcamento` varchar(50) NOT NULL,
	`status` enum('rascunho','enviada','aceita','rejeitada','expirada') DEFAULT 'rascunho',
	`nome_empresa` varchar(255) NOT NULL,
	`cnpj` varchar(18),
	`contato_principal` varchar(255),
	`email_cliente` varchar(320),
	`telefone_cliente` varchar(20),
	`endereco_cliente` text,
	`tipo_fretamento` varchar(100),
	`descricao_servico` text,
	`data_inicio` date,
	`data_termino` date,
	`frequencia` varchar(50),
	`horarios_coleta` text,
	`pontos_coleta` text,
	`destinos` text,
	`quantidade_veiculos` int,
	`tipo_veiculo` varchar(100),
	`capacidade_passageiros` int,
	`especificacoes` text,
	`valor_dia` decimal(10,2),
	`quantidade_dias` int,
	`desconto` decimal(10,2) DEFAULT 0,
	`valor_total` decimal(10,2),
	`forma_pagamento` varchar(100),
	`condicoes_especiais` text,
	`observacoes` text,
	`proposto_por` varchar(255),
	`data_proposta` date,
	`data_validade` date,
	`assinado_por` varchar(255),
	`data_assinatura` timestamp,
	`token_assinatura` varchar(255),
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_by` varchar(255),
	CONSTRAINT `propostas_id` PRIMARY KEY(`id`),
	CONSTRAINT `propostas_numero_orcamento_unique` UNIQUE(`numero_orcamento`)
);
--> statement-breakpoint
ALTER TABLE `proposta_historico` ADD CONSTRAINT `proposta_historico_proposta_id_propostas_id_fk` FOREIGN KEY (`proposta_id`) REFERENCES `propostas`(`id`) ON DELETE no action ON UPDATE no action;